# 第３回　関数、クラス、モジュールの使い方、入出力

## 関数

**関数**とは、一連の処理をまとめて記述したものです。それに名前をつけることによって、処理の内容をいちいち書かなくても、名前で簡単に呼び出して実行させることができます。

関数には、Pythonに元来備わっていう**組み込み関数**と、プログラムする人が定義する関数とがあります。これまでにたくさん使っている<b><em>print()</em></b>は、組み込み関数の代表的なものです。

ある関数がどんなものかを説明するには、名前の他に、どんな**引数**をとり、どんな**返り値**を返すか、説明する必要があります。

### 関数の作り方

Pythonでは、***def***文で関数を定義します。<u>関数の中身（具体的な処理）は、インデントを用いて字下げして記述</u>します。<br>
関数の名前とともに、**引数**（関数に引き渡す値）を定義することがあります。<br>
また、関数の処理の最後に、***return***のあとに**返り値**（関数の出力）を設定することがあります。

関数を宣言すると、関数内で宣言される変数の有効範囲が関数内に限定されます（**スコープ**といいます）。
関数の外側に同じ名前の変数があっても、関数内の変数にアクセスが行われます。
関数の外側の変数（**グローバル変数**）にアクセスするときは、***global*** **グローバル変数名**、と宣言してアクセスします。

次の関数<em>plus_one()</em>は、（十進数の）数字の各桁に１を足した（ただし、９は０にする）数字を返します。 
例えば"4567"には"5678"を、"6789"には"7890"を返します。  
次のような組み込み関数にも注目してください。  
- 数値を文字列に変換する***str()***  
- 文字列を整数に変換する***int()***  
- ***for***文と合わせて**イテレータ**（リストなど）のそれぞれの要素を取り出す***enumerate()***  

また、関数ではなくメソッドですが、<b><em>join()</em></b>の使い方にも注目してください

In [17]:
def plus_one(number):
    number_list = list(str(number))
    #数を数字のリストにするには、上のように、文字列にしてからリストにする。
    # 次のループでは、リストの添え字iと要素xの両方を処理します（テキスト133頁参照）
    for i, x in enumerate(number_list):
        x = int(x)
        #足し算ができるように、上のように文字を整数に戻してやる
        if (x != 9):
            x = x + 1
        else:
            x = 0
        number_list[i] = x
        #上の行がないと、リストの中身が書き換わらない
    number_list = [str(x) for x in number_list] #今度は、リストの要素の整数を数字に戻す必要があります。
    # for 文のこのような書き方については、テキストの74頁「リスト内包表記」を参照してください。
    number_out = "".join(number_list) # join()はリストで与えられた文字列を区切り文字で連結する、文字列のメソッドです。
    # この場合、区切り文字は""つまり何もない文字です。一般的には"|"などの区切り文字を指定します。
    number_out = int(number_out) #出力するときは、文字列を整数にします。
    return number_out #値を返すときはreturnを使います。
# この関数の使い方
ans = plus_one(4567)
print(ans)

5678


In [19]:
plus_one(3984)

4095

### 組み込み関数いろいろ

詳しくは、テキストを御覧ください。

入出力に関係するもの

|名前|説明|
|----|----|
|input|標準入力からの入力|
|print|標準出力への出力|



リストに関係するもの

文字列に関係するもの

## クラス

さきほどの例で、join()は関数ではなく**文字列クラス**の**メソッド**であると言いました。  
join()は、文字列**インスタンス**－例えば空白文字" "－のあとに"."でつなげて使います。  
（注：インスタンスinstanceの本来の意味は「具体例example」ですね。なにの「具体例」かというと、文字列「クラス」（class）の具体例なのです。）  
join()の引数は、要素が文字であるようなリストです。  
join()でできることは、文字列インスタンスを**区切り文字**として**リストの要素を連結**することです。  
次の例を見てください。

In [22]:
str(date.today())

'2022-04-26'

In [6]:
import datetime
"♥♠".join(['Hello, it is', str(datetime.date.today()), 'today.']) #3つの要素を連結しています。 

'Hello, it is♥♠2022-04-26♥♠today.'

さて、文字列"♥♠"は文字列型のデータでありますが、Pythonのような「オブジェクト指向言語」においては文字列クラスのインスタンスでもあります。つまり、Pythonにおいて、「～型」を「～クラス」と言い換えても問題ありません。

その反対に、「～クラス」は、単なるデータ型ではなく、そのデータの使い方まで定義されています。  
どういうことかというと、「～クラス」には、そのクラスのデータ（以降「インスタンス」といいます）だけを処理できるような関数が用意されています。そうした関数を、～クラスの「メソッド」といいます。

文字列クラスのメソッドを例示します。まず大文字にするupper()です。

In [52]:
string = "abcd"
print(string.upper())

ABCD


次に、文字列の置き換えをするreplace()です。

In [14]:
string2 = "I like bananas. I take two bananas every day."
print(string2.replace('bananas', 'apples'))# bananasをapplesで置き換える

I like apples. I take two apples every day.


他にも多数あります。「Python 文字列クラス　メソッド」で検索してみてください。

### クラスの作成（テキスト１６９頁～）

ユーザーが自分でクラスを定義すれば、独自にデータ型を作成できます。また、それに対するメソッドを定義できます。 
関数を定義するとき、def文を用いましたが、クラスの定義はclass文でおこないます。
メソッドの定義には、関数の定義と同様にdef文を用います。

In [11]:
class Car:  #Carクラスの定義
    def run(self):  #メソッド
        print('Car is running.')
    def turn(self, dir):
        print('Turn '+dir+'.!')

myCar = Car()       #Carクラスのインスタンスの作成
myCar.run()         #メソッドの呼び出し
myCar.turn('left')  #メソッドの呼び出し（引数あり）

Car is running.
Turn left.!


メソッドを定義するとき、その第一引数には、self というインスタンス自身をあらわす変数を置きます。それによって、メソッドの引数が何もないときは、インスタンス自身が引数として使われることになります。  
\_\_init\_\_ （initの前後にアンダースコア\_が2個ずつ）というメソッドを用いることによって、インスタンスの初期化（例えば、属性の初期値を設定する）を行います。また、このメソッドを**コンストラクタ**といいます（テキスト186頁参照）。  
次の例を見てください。

In [13]:
class City_jp:
    # クラスの名前は大文字で始めるのが慣例です。
    def __init__(self,name):
        self.name = name
    def prefecture(self):
        name = self.name
        tuple_1 = name.partition('県')
        # partition(区切り文字)は、文字列のメソッドです。
        # このメソッドは、文字列のインスタンスを処理して、
        # (区切り文字の前の文字列、区切り文字、区切り文字のあとの文字列)という３つの要素
        # をもつタプルを返します。
        return(tuple_1[0])
    def city(self):
        name = self.name
        tuple_1 = name.partition('県')
        tuple_2 = tuple_1[2].partition('市')
        return(tuple_2[0])
# このクラスの使い方
my_address = City_jp('千葉県船橋市三山２－２－１') #住所を与えて、City_jpクラスのインスタンスmy_addressを作ります
print(my_address.name) # 住所のname属性を取り出します。
print(my_address.prefecture())
# 上の行は、県名を抜き出します
# prefectureの引数は一見空っぽですが、実際はmy_addressオブジェクトそのものです。self属性を最初に定義しているからです。
print(my_address.city())
# 上の行は、市名を抜き出します

千葉県船橋市三山２－２－１
千葉
船橋


何をしたいのかは明らかだと思います。方法はまったく不十分ではあります。郡や区には対応していません。対応したとしても注意すべき例が結構あります（例：長野県小県（ちいさがた）郡, 三重県四日市市, など）

このように、クラスを定義することによって、データそのものに、データ処理の方法を付け加えることができます。

## モジュールの使い方 （テキスト１０８頁～）

すでに、「***import***　～」という形式の文を使っていますが、これは、Pythonを起動したときから使えるもの以外の「**モジュール**」(module)を利用するための「**インポート**」(import, 取り込む)命令です。

モジュールとは、Pythonで書いたプログラム群のことです。モジュールをインポートするときは、通常、より大きなモジュールである「**ライブラリ**」（library）単位で行います。  
通常 ***import モジュール名***　でインポートをおこないます。

In [15]:
import datetime # テキスト109頁参照
print(datetime.date.today())

2022-04-26


モジュールの一部（サブモジュール）をインポートすることもできます。***from モジュール名 import サブモジュール名*** のようにします。

In [16]:
from datetime import date
print(date.today())

2022-04-26


モジュールの名前が短いほうがプログラムを書きやすいので as によって別名をつけることもあります。  
次の例は、行列の回で扱いました。

In [102]:
# numpyをインポートしてnpという別名をつける
import numpy as np
# 3行2列の行列を定義する
matrix_a = np.array([[1,2],[2,3],[3,4]])
print(matrix_a)

[[1 2]
 [2 3]
 [3 4]]


## 入出力

参考書「Pythonによる統計分析入門」（山内長承著, オーム社, 2018年）の176ページで出生率と死亡率との関係を扱っています。これの表のデータが'year_birth_death.csv'というCSV形式のテキストファイルに入っているとします。このファイルを読み込んでみましょう。

Jupyter Notebookを利用していれば、Notebookフォルダーの中にこのファイルをコピーすると、ノートの一覧と並んでCSVファイルも表示されます。そして、ファイル名をダブルクリックすると内容を表示できます。１つの行が３列からなるデータだとわかります。最初の列が年、２列目が出生率、３列目が死亡率、です。

これをNumPyの<strong><em>genfromtxt()</em></strong>関数で読み込むと数値の行列ができます（CSVファイルを読み込む方法は他にもあります）。  
次の例で、<em>genfromtxt()</em>の最初の引数がファイル名です。  
また、引数としてさまざまなオプションを必要とします。***delimiter***は区切り文字、***skip_header***は最初の何行を飛ばすかを表します。このファイルでは最初の行が見出しになっていますので、１行飛ばしてデータを読み込み始めます。  
さらに、オプション***encoding***は文字コードを表します。UTF-8のファイルを作ったつもりでも、実際には*utf-8_sig*を必要とする場合があります。

In [23]:
import numpy as np
x = np.genfromtxt('year_birth_death.csv', delimiter=',', skip_header=1,encoding="utf-8_sig")

In [24]:
x

array([[1899. ,   32. ,   21.5],
       [1900. ,   32.4,   20.8],
       [1901. ,   33.9,   20.9],
       [1902. ,   33.6,   21.3],
       [1903. ,   32.7,   20.4],
       [1904. ,   31.2,   20.7],
       [1905. ,   31.2,   21.6],
       [1906. ,   29.6,   20.3],
       [1907. ,   34. ,   21.4],
       [1908. ,   34.7,   21.5],
       [1909. ,   34.9,   22.5],
       [1910. ,   34.8,   21.6],
       [1911. ,   35.1,   20.9],
       [1912. ,   34.4,   20.5],
       [1913. ,   34.3,   20. ],
       [1914. ,   34.8,   21.2],
       [1915. ,   34.1,   20.7],
       [1916. ,   33.7,   22.2],
       [1917. ,   33.5,   22.2],
       [1918. ,   32.7,   27.3],
       [1919. ,   32.3,   23.3],
       [1920. ,   36.2,   25.4],
       [1921. ,   35.1,   22.7],
       [1922. ,   34.3,   22.4],
       [1923. ,   35.2,   22.9],
       [1924. ,   33.9,   21.3],
       [1925. ,   34.9,   20.3],
       [1926. ,   34.6,   19.1],
       [1927. ,   33.4,   19.7],
       [1928. ,   34.1,   19.8],
       [19

In [28]:
# ここで、xとだけ実行すると、この行列xの中身を全部表示する。
# 最初の５行を表示する
x[0:5,]

array([[1899. ,   32. ,   21.5],
       [1900. ,   32.4,   20.8],
       [1901. ,   33.9,   20.9],
       [1902. ,   33.6,   21.3],
       [1903. ,   32.7,   20.4]])

In [30]:
# 行数（xにはいくつの要素（３つの値からなる配列）が含まれるか）を調べる。
len(x)

118

In [6]:
#１列目（year）に欠けている数字（つまりデータのない年）があるか調べる。
col_year = x[:,0] #2次元配列の一列目だけを抜き出す、2次元データのスライス指定でカンマの前が行、後ろが列を指定
year_min = int(min(col_year)) #最も古い年
year_max = int(max(col_year)) #最も新しい年
year_range = range(year_min, year_max) #最も古い年から最も新しい年までの範囲のリスト
for year in year_range:
    if year not in col_year: #抜き出した年のデータに存在していない年を表示
        print(year)

1944
1945
1946


これらの年がどうして欠けているのかは知っていますね？