# 第２回　Pythonの基礎（２）

## Pythonのデータ型

Pythonのプログラミングでは、データ型（数値とか文字列とか）を指定しなくてもプログラミングが可能ですが、特定のデータ型にしか適用できない処理がありますので、データ型を意識してプログラミングを行なう必要があります。

Pythonの主なデータ型は次の表のとおりです。論理型については前回扱いました。if文やwhile文の条件式に使われます。

|データ型|説明|
|--|--|
|数値型(number)|数値を扱うデータ型|
|論理型(boolean)|真(true)と偽(false)をとるデータ型|
|リスト型(list)|要素の集まりを扱うデータ型。順番あり。要素の変更が可能|
|タプル型(tuple)|要素の集まりを扱うデータ型。順番あり。要素の変更は不可|
|辞書型(dict)|キー(ley)と値(value)の組み合わせでできた要素の集まりを扱うデータ型。順番なし。要素の変更が可能|
|集合型(set)|要素の集まりを扱うデータ型。順番なし。要素の変更が可能|

### 数値型

Pythonでは数値は通常は浮動小数点型として処理されます。

In [1]:
0.1+0.2

0.30000000000000004

In [19]:
0.1*0.2

0.020000000000000004

そのため、小数を扱うとき、上の例のように、誤差が生じることに注意する必要があります。

桁数や小数点以下の桁数を指示して表示するときはprint関数を次のように使います。

In [21]:
print('{:.2f}'.format(0.1+0.25))
#小数点以下２桁まで表示

0.35


In [22]:
print('{:10}'.format(111.1+0.25))
#10桁で表示

    111.35


あとの例では、先頭に空白が4桁挿入されることによって全体の桁数が10になっています。

文字列型

文字列はシングルクォーテーション、ダブルクォーテーション、三重引用符のどれかで囲んで使います。三重引用符を使うと改行を含む文字列を扱うことができます。

In [28]:
string_ex1 = 'abc'
string_ex2 = "def"
string_ex3 = """hij
klm"""
print(string_ex1)
print(string_ex2)
print(string_ex3)

abc
def
hij
klm


文字列の演算

数値では足し算の'+'は、文字列では連結を表します。

In [5]:
print('abc'+'def')

abcdef


同値判定を行う'=='あるいは'!='も文字列が同じであるかどうかの判定に使えます。

In [6]:
'acc' == 'acc'

True

In [9]:
'acc' != 'acc'

False

文字列に対する操作

In [22]:
string = '   Hello, World!   '
string.lower()
#すべて小文字にしたものを返す。

'   hello, world!   '

In [23]:
string.lstrip()
#先頭の空白文字を除去したものを返す
#先ほどの操作でオブジェクトそのものは変化していないことに注意。

'Hello, World!   '

In [24]:
string.rstrip()
#末尾の空白文字を除去したものを返す。

'   Hello, World!'

In [25]:
string.strip()
#先頭と末尾の空白文字を除去したものを返す。

'Hello, World!'

In [26]:
string.upper()
#すべて大文字にしたものを返す。

'   HELLO, WORLD!   '

In [19]:
string.split(' ')
#スペースを区切り文字にして分割しリストにしたものを返す。

['', '', '', 'Hello,', 'World!', '', '', '']

In [21]:
string.strip().split(' ')

['Hello,', 'World!']

上に挙げた文字列操作は、「文字列クラス」の「メソッド」を用いました。

要素をもつデータ型:リスト、タプル、辞書等

複数の要素をもつデータ型を複合（compound）データ型といいます。処理を繰り返すときに使うのでイテレータ（iterator）ともいいます。

リスト

リストは、コンマ区切りの値（要素）の並びを角カッコで囲んだものとして記述されます。

In [2]:
squares = [1, 4, 9, 16, 25, 36]

要素には先頭から0, 1, 2, ...の「添字」がついています。これを利用して特定の要素を取り出すことができます。

In [27]:
squares = [1, 4, 9, 16, 25, 36]
print(squares[1])
#2番目の要素を印字する

4


また、末尾から-1, -2, ..., -N (Nは要素数）の添字が付いています。これを利用しても、特定の要素を取り出すことができます。

In [28]:
squares = [1, 4, 9, 16, 25, 36]
print(squares[-2])
#末尾から２番めの要素を印字する

25


リストの一部を取り出す（スライス）

角括弧（[]）の中に「始点の添字:終点の添字+1」を書くことによってリストの一部を連続的に取り出すことができます。

In [29]:
squares = [1, 4, 9, 16, 25, 36]
print(squares[0:3])
#1番目（添字は0）から3番目（添字は2）までの要素を印字する

[1, 4, 9]


始点または終点の添字の片方を省略することができます。
それによって、次の示すように、ある要素から最後の要素までを取り出すことができます。

In [30]:
squares = [1, 4, 9, 16, 25, 36]
print(squares[3:])
#４番め（添字は3）から最後までを印字する

[16, 25, 36]


同様にして、最初からある要素までを取りだすことができます。

In [31]:
squares = [1, 4, 9, 16, 25, 36]
print(squares[:3])
#最初から３番め（添字２）までの要素を印字する。

[1, 4, 9]


リストは要素を書き換えることができます。  
例えば、すべての要素の値に1を足すにはenumerate()関数を用いて次のようにします。

In [10]:
#まずリストsquaresを作る。
squares = [i**2 for i in range(1,7)]
#range()関数の引数は、(下限（省略したら0）,上限（ただし、越えない値）, ステップ（省略したら1） )であることに注意。
print(squares)
#次にリストsquaresの各要素に1を足す
for i, square in enumerate(squares):
    #添字がi, 要素の値はsquare
    squares[i] = square + 1
print(squares)

[1, 4, 9, 16, 25, 36]
[2, 5, 10, 17, 26, 37]


上のプログラムで、リストsquaresを初期化して最初の値を埋めるには、次のようにもできます。

In [15]:
squares = list()
# これは、squares = []と同じ。
for i in range(1,7):
    squares.append(i**2)
print(squares)

[1, 4, 9, 16, 25, 36]


タプル

タプルは、リストと違って、変更不可能です。添字のしかたはリストと同じです。

In [33]:
tuple_ex = (2,3,4,5,6)

In [34]:
tuple_ex[0]

2

In [40]:
tuple_ex[0] = 1
#変更しようとするとエラーが出る

TypeError: 'tuple' object does not support item assignment

In [41]:
list_ex = [x for x in tuple_ex]
#タプルの内容をリストにコピーしてみる

In [37]:
list_ex

[2, 3, 4, 5, 6]

In [42]:
list_ex[0] = 1
#リストは変更可能
print(list_ex[0])

1


辞書

辞書型は、キー（key）と値（value）の組み合わせの集まりです。順番はありません。キーをインデックス（索引）として使い、キーに対する値を取り出します。

In [4]:
capital = {'United Kingdom':'London','Australia':'Canberra'}
print(capital['United Kingdom'])

London


集合

集合型は、重複する要素をもたない、順序のない、要素の集まりです。次の例のように、集合演算が可能です。

In [17]:
set_a = {3,6,9,12,15 }
set_b = {6,12,18}
#積集合を求める
set_c = set_a.intersection(set_b)
print(set_c)
#和集合を求める
set_d = set_a.union(set_b)
print(set_d)
#差を求める
set_e = set_b.difference(set_a)
set_f = set_a.difference(set_b)
print("set_bだけ:{0}".format(set_e))
print("set_aだけ:{0}".format(set_f))

{12, 6}
{18, 3, 6, 9, 12, 15}
set_bだけ:{18}
set_aだけ:{9, 3, 15}


## 行列とNumPy

NumPyという外部ライブラリ（標準のPythonには含まれない）の配列クラス（numpy.array）には配列（ベクトル）や行列の操作のために便利なメソッドが多く用意されています。（注：「クラス」と「メソッド」については回を改めて説明します。今は、クラスとはより複雑なデータの型、メソッドとはあるクラス用の関数（関数についても回を改めて説明します）である、くらいに理解してください。）

NumPyをインポートする

NumPyは外部ライブラリですので、使うためにインポートする必要があります。

In [2]:
import numpy as np

直訳するなら、「numpyをnpとして読み込む」となります。このように書くことで、これ以降、NumPyに関するメソッドはnpとして参照することができます。

NumPyで配列を作る

np.array()というメソッドを用います。np.array()は、リストを引数にとり、NumPy用の配列（numpy.ndarrayクラス）を生成します。

In [5]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)
#オブジェクトの型を取得

[1. 2. 3.]


numpy.ndarray

NumPyによる配列の算術計算

In [14]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print("要素ごとの和:{0}".format(x + y))
print("要素ごとの積:{0}".format(x * y))
print("要素ごとの商:{0}".format(x / y))
print("xと2のスカラ積:{0}".format(2*x))

要素ごとの和:[3. 6. 9.]
要素ごとの積:[ 2.  8. 18.]
要素ごとの商:[0.5 0.5 0.5]
xと2のスカラ積:[2. 4. 6.]


NumPyによる行列（２次元配列）

行列どうしの要素ごとの和や積や商、そして、行列のスカラ積（行列の各要素を単純に何倍かする）も、配列と同じ書き方でできます。

In [28]:
import numpy as np
A = np.array([[1.0, 2.0], [3.0, 4.0]])
B = np.array([[3.0, 0], [0, 6.0]])
print("行列の表示")
print("A={0}".format(A))
print("B={0}".format(B))
print("行列Aの形")
print(A.shape)
print("行列Aの要素のデータ型")
print(A.dtype)
print("行列の要素ごとの和 A + B = ")
print(A + B)
print("行列の要素ごとの積 A * B = ")
print(A * B)
print("行列のスカラ積 2A = ")
print(2*A)

行列の表示
A=[[1. 2.]
 [3. 4.]]
B=[[3. 0.]
 [0. 6.]]
行列Aの形
(2, 2)
行列Aの要素のデータ型
float64
行列の要素ごとの和 A + B = 
[[ 4.  2.]
 [ 3. 10.]]
行列の要素ごとの積 A * B = 
[[ 3.  0.]
 [ 0. 24.]]
行列のスカラ積 2A = 
[[2. 4.]
 [6. 8.]]


行列どうしの積は、ベクトル（つまりNumPyの配列）どうしの「ドット積」（内積のことです）の組合わせです。ドット積とは、２つのベクトルが例えば
$$
x = (a, b), y = (c, d)
$$
であるとすると、
$$
x.y = ac + bd
$$
というスカラー（数値）を作る演算です

行列どうしの積は、例えば2 x 2行列では次のように定義されます、
$$
A=\left(
\begin{matrix} a & b \\ c & d \end{matrix}
\right)
, B=\left(
\begin{matrix} p & q \\ r & s \end{matrix}
\right)
$$
とすると、
$$
AB = \left(
\begin{matrix} ap + br & aq + bs\\ cp + dr & cq + ds \end{matrix}
\right)
$$
となります。このように、積ABでできる行列のi行j列の要素は、行列Aのi行めと行列Bのj列めのドット積になっています。
<BR>このことは次の２つのことを意味します。（１）ふつうは、積ABと積BAの結果は異なる（２）Aの列の数とBの行の数が同じでないと、積ABが定義できない。

ドット積を計算するNumPyの関数は、np.dot()です。

In [33]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 7], [11, 13]])
print("A = ")
print(A)
print("B = ")
print(B)
print("行列の積")
print("AB=")
C = np.dot(A,B)
print(C)
print("BA=")
D = np.dot(B,A)
print(D)

A = 
[[1 2]
 [3 4]]
B = 
[[ 5  7]
 [11 13]]
行列の積
AB=
[[27 33]
 [59 73]]
BA=
[[26 38]
 [50 74]]


行列の要素へのアクセス（例：行や列を取り出す）

次のようにして行列の要素にアクセスできます。

In [39]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 7], [11, 13]])
print("A = ")
print(A)
print("B = ")
print(B)
print("Aの1行目を取り出す")
print(A[0])
print("Bの1列目を取り出す")
print(B[:,0])
print("Aの1行目とBの1列目のドット積を計算する")
print(np.dot(A[0],B[:,0]))

A = 
[[1 2]
 [3 4]]
B = 
[[ 5  7]
 [11 13]]
Aの1行目を取り出す
[1 2]
Bの1列目を取り出す
[ 5 11]
Aの1行目とBの1列目のドット積を計算する
27
